### ISSUE TITLE
Replace opensuse:leap with opensuse/leap

### ISSUE THREAD

**Issue by h6w** [bmanojlovic/cross-qnap-i-c#1]
Opensuse:leap docker image doesn't exist any more.

The [opensuse repos on Dockerhub](https://hub.docker.com/_/opensuse/) says 

> DEPRECATED - for current images by the openSUSE Project see opensuse/leap and opensuse/tumbleweed.

Replacing `opensuse:leap` with `opensuse/leap` in `Dockefile.arm` and `Dockerfile.x86` at least allows it to build.  I'm yet to verify it works, though.

**Comment by bmanojlovic** [comment]
done
